SignupPractice/Models/Identity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace SignupPractice.Models
{
    public class Identity
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public long phone { get; set; }
    }

    public class IdentityDBContext : DbContext
    {
        public DbSet<Identity> Identies { get; set; }

        public int? identitycheck(string c_email, string c_password, out Identity identity)
        {
            identity = null;
            if( null != (identity = Identies.SingleOrDefault(x => x.email == c_email))) //email verified
            {
                if (identity.password == c_password) // password varified
                    return identity.id;
                return null;
            }
            return null;
        }
    }
}

SignupPractice/Controllers/IdentitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SignupPractice.Models;

namespace SignupPractice.Controllers
{
    //lets do it .....
    public class IdentitiesController : Controller
    { 
//Ali here and i am about to begin
        private IdentityDBContext db = new IdentityDBContext();
        private static int? authorized_user_id = null;
        // GET: Identities
        public ActionResult Index(int? id )/*TODO: int? id*/ //done
        {
            if (id == null)
                return HttpNotFound();
            else if (authorized_user_id != id) // TODO: Login validation required... //done
                return RedirectToAction("Login");
            else
            {
                ViewBag.Authentication = true;
                return View(db.Identies.Find(id));/*TODO: pass identity*/ //done
            }    
        }

        // GET: Identities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Identity identity = db.Identies.Find(id);
            if (identity == null)
            {
                return HttpNotFound();
            }
            else if (authorized_user_id == id)
                return View(identity); // TODO: Login validation required... // done
            else
                return RedirectToAction("Login");
        }

        // GET: Identities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Identities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,firstname,lastname,email,password,phone")] Identity identity)
        {
            if (ModelState.IsValid)
            {
                db.Identies.Add(identity);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = identity.id });
            }

            return View(identity);
        }

        // GET: Identities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Identity identity = db.Identies.Find(id);
            if (identity == null)
            {
                return HttpNotFound();
            }
            else if (authorized_user_id == id)
                return View(identity); // TODO: Login validation required... //done
            else
                return RedirectToAction("Login");
        }

        // POST: Identities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,firstname,lastname,email,password,phone")] Identity identity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(identity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = identity.id });
            }
            return View(identity);
        }

        // GET: Identities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Identity identity = db.Identies.Find(id);
            if (identity == null)
            {
                return HttpNotFound();
            }
            else if (authorized_user_id == id)
                return View(identity); // TODO: Login validation required... //done
            else
                return RedirectToAction("Login");
        }

        // POST: Identities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Identity identity = db.Identies.Find(id);
            db.Identies.Remove(identity);
            db.SaveChanges();
            return RedirectToAction("Index", "Home"); //TODO: change //done
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "email,password")] Identity identity)
        {
            int? myidentity; Identity validIdentity = null;
            if(null == (myidentity = db.identitycheck(identity.email, identity.password, out validIdentity)))
            {
                ViewBag.Message = "login failed"; 
                return View();
            }
            //ViewBag.Message = myidentity + "login successfull";
            authorized_user_id = myidentity;
            return RedirectToAction("Index", new { id = myidentity });
        }
        public ActionResult Logout()
        {
            authorized_user_id = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

SignupPractice/Controllers/ProjectsEntitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SignupPractice.Models;

namespace SignupPractice.Controllers
{
    public class ProjectsEntitiesController : Controller
    {
        private ProjectsEntityDBContext db = new ProjectsEntityDBContext();

        public PartialViewResult hello()
        {
            return PartialView(db.projectsEntities.ToList());
        }
        // GET: ProjectsEntities
        public ActionResult Index()
        {
            return View(db.projectsEntities.ToList());
        }

        // GET: ProjectsEntities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectsEntity projectsEntity = db.projectsEntities.Find(id);
            if (projectsEntity == null)
            {
                return HttpNotFound();
            }
            return View(projectsEntity);
        }

        // GET: ProjectsEntities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProjectsEntities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,title,field,dateofcreation,deadline,teacher_id,progress")] ProjectsEntity projectsEntity)
        {
            if (ModelState.IsValid)
            {
                db.projectsEntities.Add(projectsEntity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(projectsEntity);
        }

        // GET: ProjectsEntities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectsEntity projectsEntity = db.projectsEntities.Find(id);
            if (projectsEntity == null)
            {
                return HttpNotFound();
            }
            return View(projectsEntity);
        }

        // POST: ProjectsEntities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,title,field,dateofcreation,deadline,teacher_id,progress")] ProjectsEntity projectsEntity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(projectsEntity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(projectsEntity);
        }

        // GET: ProjectsEntities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectsEntity projectsEntity = db.projectsEntities.Find(id);
            if (projectsEntity == null)
            {
                return HttpNotFound();
            }
            return View(projectsEntity);
        }

        // POST: ProjectsEntities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProjectsEntity projectsEntity = db.projectsEntities.Find(id);
            db.projectsEntities.Remove(projectsEntity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SignupPractice/Controllers/TeacherEntitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SignupPractice.Models;

namespace SignupPractice.Controllers
{
    public class TeacherEntitiesController : Controller
    {
        private TeacherEntityDBContext db = new TeacherEntityDBContext();
        private static int? authorized_user_id = null;
        // GET: TeacherEntities
        public ActionResult Index(int? id)
        {
            if (id == null)
                return HttpNotFound();
            else if (authorized_user_id != id) // TODO: Login validation required... //done
                return RedirectToAction("Login");
            else
            {
                ViewBag.Authentication = true;
                return View(db.teacherEntities.Find(id));/*TODO: pass identity*/ //done
            }
            //return View(db.teacherEntities.ToList());
        }

        // GET: TeacherEntities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeacherEntity teacherEntity = db.teacherEntities.Find(id);
            if (teacherEntity == null)
            {
                return HttpNotFound();
            } 
            else if (authorized_user_id == id)
                return View(teacherEntity); // TODO: Login validation required... //done
            else
                return RedirectToAction("Login");
        }

        // GET: TeacherEntities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TeacherEntities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,firstname,lastname,designation,email,password,phone")] TeacherEntity teacherEntity)
        {
            if (ModelState.IsValid)
            {
                db.teacherEntities.Add(teacherEntity);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = teacherEntity.id});
            }

            return View(teacherEntity);
        }

        // GET: TeacherEntities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeacherEntity teacherEntity = db.teacherEntities.Find(id);
            if (teacherEntity == null)
            {
                return HttpNotFound();
            }
            else if (authorized_user_id == id)
                return View(teacherEntity);  // TODO: Login validation required... //done
            else
                return RedirectToAction("Login"); 
        }

        // POST: TeacherEntities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,firstname,lastname,designation,email,password,phone")] TeacherEntity teacherEntity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(teacherEntity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = teacherEntity.id});
            }
            return View(teacherEntity);
        }

        // GET: TeacherEntities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeacherEntity teacherEntity = db.teacherEntities.Find(id);
            if (teacherEntity == null)
            {
                return HttpNotFound();
            }
            else if (authorized_user_id == id)
                return View(teacherEntity);   // TODO: Login validation required... //done
            else
                return RedirectToAction("Login");
        }

        // POST: TeacherEntities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TeacherEntity teacherEntity = db.teacherEntities.Find(id);
            db.teacherEntities.Remove(teacherEntity);
            db.SaveChanges();
            return RedirectToAction("Index", "Home"); //TODO: change //done
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "email,password")] TeacherEntity teacherEntity)
        {
            int? myidentity; TeacherEntity validIdentity = null;
            if (null == (myidentity = db.identitycheck(teacherEntity.email, teacherEntity.password, out validIdentity)))
            {
                ViewBag.Message = "login failed";
                return View();
            }
            //ViewBag.Message = myidentity + "login successfull";
            authorized_user_id = myidentity;
            return RedirectToAction("Index", new { id = myidentity });
        }
        public ActionResult Logout()
        {
            authorized_user_id = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

SignupPractice/Views/Identities/Create.cshtml
@model SignupPractice.Models.Identity

@{
    ViewBag.Title = "Create";
}

<h2>Signing up as Student</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="container">
    <div class="col-md-6">
        <div class="form-horizontal">
            @*<h4>Identity</h4>*@
            
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
                </div>
            </div>
            <div>
                @Html.ActionLink("Already have account??", "Login", "Identities") @*idid*@
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6 text-center">
        <p>@Html.ActionLink("Signup as Teacher", "Create", "TeacherEntities", null, new { @class = "btn btn-info btn-lg" })</p>
    </div>
</div>

}

            @*<div>
                    @Html.ActionLink("Back to List", "Index")
                </div>*@

            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }

SignupPractice/Views/Identities/Delete.cshtml
@model SignupPractice.Models.Identity

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Identity</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", new { id = Model.id })
        </div>
    }
</div>

SignupPractice/Views/Identities/Details.cshtml
@model SignupPractice.Models.Identity

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Identity</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index", new { id = Model.id })
</p>

SignupPractice/Views/Identities/Index.cshtml
@*@model IEnumerable<SignupPractice.Models.Identity>*@
@model SignupPractice.Models.Identity

@if (ViewBag.Authentication == true)
{
    {
        Layout = "~/Views/Shared/_LayoutS.cshtml";
    }
}
else
{
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}


@{
    ViewBag.Title = "Index";
    ViewBag.username = Model.firstname + " " + Model.lastname;
}

<div class="container">

    <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked">
            <li><a data-toggle="pill" href="#profile">Your Profile</a></li>
            <li><a data-toggle="pill" href="#projectsearch">Search Projects</a></li>
        </ul>
    </div>

    <div class="col-md-10">
        <div class="tab-content">
            <div id="profile" class="tab-pane fade in active">

                <div class="container"> @*profile*@
                <div class="panel ">
                    <div class="panel-body">
                        <div class=" col-md-4 text-center">
                        <img class="img-thumbnail" style="width:200px; height:200px;" src="#" />
                        </div>
                        <div class=" col-md-8">
                            <h2>STUDENT NAME</h2>
                            <p>details..</p>
                        </div>                        
                    </div>
                </div>
                </div>

                <h2>Your Projects</h2><hr />
                <div class="panel panel-default" style="width:20rem;">
                    <div class="panel-heading"><h3>Project title</h3></div>
                    <div class="panel-body">                      
                        <div class="panel-info"><p> helo ae eamf fd rknam f ldsjen sdkles nd dlfkns </p></div>
                        <a href="#" class="btn btn-primary">click</a> 
                    </div>
                </div>
            </div>
            <div id="projectsearch" class="tab-pane fade">
                <h3>Projects list which is being offered</h3>
                @{
                    Html.RenderAction("hello", "ProjectsEntities");
                 }
                <p>search functionality Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            </div>               
        </div>
    </div>

</div>
<div class="container">
    <div class="col-md-10">
        @*<p>
                @Html.ActionLink("Create New", "Create")
            </p>*@
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.firstname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.lastname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.password)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.phone)
                </th>
                <th></th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => Model.id)
                </td>
                <td>
                    @Html.DisplayFor(model => Model.firstname)
                </td>
                <td>
                    @Html.DisplayFor(model => Model.lastname)
                </td>
                <td>
                    @Html.DisplayFor(model => Model.email)
                </td>
                <td>
                    @Html.DisplayFor(model => Model.password)
                </td>
                <td>
                    @Html.DisplayFor(model => Model.phone)
                </td>
                @try
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
                        @Html.ActionLink("Details", "Details", new { id = Model.id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = Model.id })
                    </td>
                }
                catch
                {

                }
            </tr>
        </table>
    </div>
</div>

SignupPractice/Views/Identities/Login.cshtml
@model SignupPractice.Models.Identity
@*@{
        Layout = "~/Views/Shared/_Layout2.cshtml";
    }*@
@{
    ViewBag.Title = "Login";
}

<h2>@ViewBag.Title as Student</h2>
<p>Please enter your valid email address and password</p>
<p>@ViewBag.Message</p>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="col-md-6">
            <div class="form-horizontal">
                @*<h4>Identity</h4>*@
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @*@Html.HiddenFor(model => model.id)*@
                @*<div class="form-group">
                        @Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                @*<div class="form-group">
                        @Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                <div class="form-group">
                    @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                    </div>
                </div>
                @*<div class="form-group">
                        @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                <div>
                    @Html.ActionLink("Don't have an account??", "Create", "Identities") @*idid*@
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Login" class="btn btn-success" />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 text-center">
            <p>@Html.ActionLink("Login as Teacher", "Login", "TeacherEntities", null, new { @class = "btn btn-info btn-lg" })</p>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}